# Generated by Django 5.2.4 on 2025-08-10 18:20

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_course_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=22, max_length=50, prefix='cart-', unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=22, max_length=50, prefix='cert-', unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=22, max_length=50, prefix='course-', unique=True),
        ),
        migrations.AlterField(
            model_name='enrolledcourse',
            name='enrollment_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=22, max_length=50, prefix='enrol-', unique=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='12345abcdefgh', length=22, max_length=50, prefix='lecture-', unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=22, max_length=50, prefix='note-', unique=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='qa_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=22, max_length=50, prefix='qa-', unique=True),
        ),
        migrations.AlterField(
            model_name='questionanswerresponse',
            name='qam_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=22, max_length=50, prefix='qam-', unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=22, max_length=50, prefix='section-', unique=True),
        ),
    ]
